"""empty message

Revision ID: bd80447caa6b
Revises: 
Create Date: 2019-06-13 12:40:30.974841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd80447caa6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ICCID', sa.String(length=255), nullable=True),
    sa.Column('IMSI', sa.String(length=255), nullable=True),
    sa.Column('Ki', sa.String(length=255), nullable=True),
    sa.Column('PIN1', sa.String(length=255), nullable=True),
    sa.Column('PUC', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('joined', sa.DateTime(), nullable=True),
    sa.Column('MSISDN', sa.String(length=12), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ICCID'),
    sa.UniqueConstraint('MSISDN')
    )
    op.create_index(op.f('ix_sim_card_id'), 'sim_card', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sim_card_id'), table_name='sim_card')
    op.drop_table('sim_card')
    # ### end Alembic commands ###
